=== matt-roz/YGOJSON/schema/v1/card.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/card.json",
  "title": "Card",
  "description": "A logical Yu-Gi-Oh card (as opposed to a physical card, of which belongs to a set).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "text",
    "cardType",
    "passwords",
    "images",
    "sets",
    "legality",
    "externalIDs",
    "series"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/card.json"
    },
    "id": {
      "description": "The UUID of this card. The name of the card's file should be this UUID.",
      "type": "string",
      "format": "uuid"
    },
    "text": {
      "description": "A map of languages to textual card information.",
      "type": "object",
      "propertyNames": {
        "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/language.json"
      },
      "additionalProperties": {
        "description": "Textual information on the card.",
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "description": "The name of the card.",
            "type": "string"
          },
          "effect": {
            "description": "All text in the main text box of the card. (Normal monster flavor also goes here, despite the name.) Null if the card's text is unknown or untranslated.",
            "type": "string"
          },
          "pendulumEffect": {
            "description": "All text in the pendulum text box of the card. Only appears on pendulum cards.",
            "type": "string"
          },
          "official": {
            "description": "Is this translation official or not? Default is true.",
            "type": "boolean"
          }
        }
      }
    },
    "cardType": {
      "description": "The broadest category of card (monster, spell, trap, etc.)",
      "enum": [
        "monster",
        "spell",
        "trap",
        "token",
        "skill"
      ]
    },
    "attribute": {
      "description": "The monster attribute. Only appears on monster or token cards.",
      "enum": [
        "light",
        "dark",
        "fire",
        "water",
        "wind",
        "earth",
        "divine"
      ]
    },
    "monsterCardTypes": {
      "description": "What summoning types this card is, if any. Only appears on monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "ritual",
          "fusion",
          "synchro",
          "xyz",
          "pendulum",
          "link"
        ]
      }
    },
    "type": {
      "description": "The race of monster. Only appears on monster or token cards.",
      "enum": [
        "beastwarrior",
        "zombie",
        "fiend",
        "dinosaur",
        "dragon",
        "beast",
        "illusion",
        "insect",
        "wingedbeast",
        "warrior",
        "seaserpent",
        "aqua",
        "pyro",
        "thunder",
        "spellcaster",
        "plant",
        "rock",
        "reptile",
        "fairy",
        "fish",
        "machine",
        "divinebeast",
        "psychic",
        "creatorgod",
        "wyrm",
        "cyberse"
      ]
    },
    "classifications": {
      "description": "Any non-type, non-ability categories appearing on the type line (effect, normal, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "normal",
          "effect",
          "pendulum",
          "tuner",
          "specialsummon"
        ]
      }
    },
    "abilities": {
      "description": "Any non-type, ability categories appearing on the type line (toon, spirit, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "toon",
          "spirit",
          "union",
          "gemini",
          "flip"
        ]
      }
    },
    "level": {
      "description": "The level of this card. Only appears on non-link, non-xyz monster or token cards.",
      "type": "integer"
    },
    "rank": {
      "description": "The rank of this card. Only appears on xyz monster cards.",
      "type": "integer"
    },
    "atk": {
      "description": "The ATK of the card. Either a number, or '?'. Only appears on monster or token cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "def": {
      "description": "The DEF of the card. Either a number, or '?'. Only appears on non-link monster cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "scale": {
      "description": "The pendulum scale. Only appears on pendulum monster cards.",
      "type": "integer"
    },
    "linkArrows": {
      "description": "The link arrows on this card. Only appears on link monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "topleft",
          "topcenter",
          "topright",
          "middleleft",
          "middleright",
          "bottomleft",
          "bottomcenter",
          "bottomright"
        ]
      }
    },
    "subcategory": {
      "description": "The type of spell/trap card this is. Only appears on spell/trap cards.",
      "enum": [
        "normal",
        "continuous",
        "equip",
        "quickplay",
        "field",
        "ritual",
        "counter"
      ]
    },
    "character": {
      "description": "The character a skill card corresponds to. Only present in skill cards.",
      "type": "string"
    },
    "skillType": {
      "description": "The card type a skill card is. Only present in skill cards.",
      "type": "string"
    },
    "passwords": {
      "description": "All official passwords given for the card.",
      "type": "array",
      "items": {
        "description": "A password, as printed on the card.",
        "type": "string",
        "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
      }
    },
    "images": {
      "description": "Card images, one per art variant. These images are generic to the card, generated automatically and in English, rather than being the image of a specific printing.",
      "type": "array",
      "items": {
        "description": "An image for a specific art treatment of a card.",
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "description": "The UUID of this art treatment. Used to refer to specific art treatments from specific printings.",
            "type": "string",
            "format": "uuid"
          },
          "password": {
            "description": "The password this art is given to. Some cards have multiple passwords, one per art. Some cards have multiple arts with the same password. And some have both going on. Not present if the card's password is currently unknown, or the card has no passwords, such as is the case for tokens.",
            "type": "string",
            "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
          },
          "art": {
            "description": "An art crop of this card.",
            "type": "string",
            "format": "uri"
          },
          "card": {
            "description": "An image of this card.",
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "sets": {
      "description": "A list of sets each card was (or will be) found in. Look up these UUIDs in the set JSON for printing information.",
      "type": "array",
      "items": {
        "description": "A UUID of the set this card appears in.",
        "type": "string",
        "format": "uuid"
      }
    },
    "illegal": {
      "description": "If true, then this card is illegal, and will not have any legality history. Never set for cards that are not game pieces, such as tokens.",
      "type": "boolean"
    },
    "legality": {
      "description": "A mapping of formats to legalities.",
      "type": "object",
      "propertyNames": {
        "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/format.json"
      },
      "additionalProperties": {
        "description": "Legality information for this format. Never set for cards that are illegal or are not game pieces (such as tokens).",
        "type": "object",
        "required": [
          "current"
        ],
        "properties": {
          "current": {
            "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/legality.json",
            "description": "The current legality of this card. Deprecated; use 'currentLegality' instead.",
            "deprecated": true
          },
          "currentLegality": {
            "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/legality.json",
            "description": "The current legality of this card. Use this to avoid reading the legality history, or use this when the legality history is unknown/empty."
          },
          "currentPoints": {
            "description": "The current point cost of this card, for formats that use points. Use this to avoid reading the legality history, or use this when the legality history is unknown/empty.",
            "type": "number"
          },
          "history": {
            "description": "The legality history for this card. Only present if this history is known, but may be empty even if known, in the case of cards whose legality has never changed.",
            "type": "array",
            "items": {
              "description": "A record of a change in legality.",
              "type": "object",
              "required": [
                "legality",
                "date"
              ],
              "properties": {
                "legality": {
                  "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/legality.json",
                  "description": "What the legality was changed to."
                },
                "points": {
                  "description": "What the point cost was changed to, for formats that use points.",
                  "type": "number"
                },
                "date": {
                  "description": "The date of the change.",
                  "type": "string",
                  "format": "date"
                }
              }
            }
          }
        }
      }
    },
    "masterDuel": {
      "description": "Any Master Duel specific information. Only present if this card is in Master Duel.",
      "type": "object",
      "required": [
        "rarity",
        "craftable"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        },
        "craftable": {
          "description": "Is this card craftable using dust?",
          "type": "boolean"
        }
      }
    },
    "duelLinks": {
      "description": "Any Duel Links specific information. Only present if this card is in Duel Links.",
      "type": "object",
      "required": [
        "rarity"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        }
      }
    },
    "externalIDs": {
      "description": "IDs and other information, to access this card from various other sites.",
      "type": "object",
      "required": [],
      "properties": {
        "yugipedia": {
          "description": "Information for Yugipedia. This array is usually 1 element long, but some cards, like Polymerizarion or the God Cards, have multiple Yugipedia pages that represent the same card.",
          "type": "array",
          "items": {
            "description": "A Yugipedia page.",
            "type": "object",
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "name": {
                "description": "The page name for this card.",
                "type": "string"
              },
              "id": {
                "description": "The internal wiki ID for the page for this card.",
                "type": "integer"
              }
            }
          }
        },
        "dbID": {
          "description": "The CID this card has on db.yugioh-card.com.",
          "type": "integer"
        },
        "ygoprodeck": {
          "description": "Information for YGOProDeck, if available",
          "type": "object",
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "name": {
              "description": "The slug for YGOProDeck you can use after 'ygoprodeck.com/card/' to get the card's page.",
              "type": "string"
            },
            "id": {
              "description": "The internal ID in YGOProDeck for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
              "type": "integer"
            }
          }
        },
        "yugiohpricesName": {
          "description": "The slug for YugiohPrices and YugiohTopDecks you can use to get the card's page. Deprecated; YugiohPrices no longer exists.",
          "type": "string",
          "deprecated": true
        },
        "yamlyugiID": {
          "description": "The internal ID in YamlYugi for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
          "type": "integer"
        }
      }
    },
    "errata": {
      "description": "Present only if this card has recieved errata. Details how the card has changed over time. Does not cover format legality information.",
      "type": "object",
      "required": [
        "original",
        "history"
      ],
      "properties": {
        "original": {
          "description": "What is the original state of the card, as first printed? A subset of the card json, with only changed properties present.",
          "type": "object"
        },
        "history": {
          "description": "The change history.",
          "type": "array",
          "items": {
            "description": "A change.",
            "type": "object",
            "required": [
              "date",
              "changes",
              "official"
            ],
            "properties": {
              "date": {
                "description": "The date of the change.",
                "type": "string",
                "format": "date"
              },
              "changes": {
                "description": "What changed with this errata. A subset of the card json, with only changed properties present.",
                "type": "object"
              },
              "official": {
                "description": "Was this change official? Unofficial changes may occur in the case of a temporary name/text beging updated when a card officially comes out in that locale.",
                "type": "boolean"
              }
            }
          }
        }
      }
    },
    "series": {
      "description": "Any series or archetypes this card is a part of.",
      "type": "array",
      "items": {
        "description": "The UUID of the series. Look it up in the series JSON.",
        "type": "string",
        "format": "uuid"
      }
    }
  }
}

=== matt-roz/YGOJSON/cards/32cd856f-6f87-4324-a3d6-bc35fb33e494.json
{
  "$schema": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/card.json",
  "id": "32cd856f-6f87-4324-a3d6-bc35fb33e494",
  "text": {
    "en": {
      "name": "Violet Witch",
      "effect": "If this card is destroyed by battle and sent to the Graveyard: Add 1 Plant-Type monster with 1500 or less DEF from your Deck to your hand."
    },
    "fr": {
      "name": "Sorci\u00e8re Violette",
      "effect": "Si cette carte est d\u00e9truite au combat et envoy\u00e9e au Cimeti\u00e8re : ajoutez 1 monstre de Type Plante avec max. 1500 DEF depuis votre Deck \u00e0 votre main."
    },
    "de": {
      "name": "Violette Hexe",
      "effect": "Falls diese Karte durch Kampf zerst\u00f6rt und auf den Friedhof gelegt wird: F\u00fcge deiner Hand 1 Monster vom Typ Pflanze mit 1500 oder weniger DEF von deinem Deck hinzu."
    },
    "it": {
      "name": "Strega Viola",
      "effect": "Se questa carta viene distrutta in battaglia e mandata al Cimitero: aggiungi 1 mostro di Tipo Pianta con DEF di 1500 o inferiore dal tuo Deck alla tua mano."
    },
    "pt": {
      "name": "Bruxa Violeta",
      "effect": "Se este card for destru\u00eddo em batalha e enviado para o Cemit\u00e9rio: adicione 1 monstro do Tipo Planta com 1500 ou menos de DEF do seu Deck \u00e0 sua m\u00e3o."
    },
    "es": {
      "name": "Bruja Violeta",
      "effect": "Si esta carta es destruida en batalla y mandada al Cementerio: a\u00f1ade a tu mano 1 monstruo de Tipo Planta con 1500 DEF o menos en tu Deck."
    },
    "ja": {
      "name": "\u30d0\u30a4\u30aa\u30ec\u30c3\u30c8\u30fb\u30a6\u30a3\u30c3\u30c1",
      "effect": "\u3053\u306e\u30ab\u30fc\u30c9\u304c\u6226\u95d8\u306b\u3088\u3063\u3066\u7834\u58ca\u3055\u308c\u5893\u5730\u3078\u9001\u3089\u308c\u305f\u6642\u3001\u81ea\u5206\u306e\u30c7\u30c3\u30ad\u304b\u3089\u5b88\u5099\u529b\uff11\uff15\uff10\uff10\u4ee5\u4e0b\u306e\u690d\u7269\u65cf\u30e2\u30f3\u30b9\u30bf\u30fc\uff11\u4f53\u3092\u624b\u672d\u306b\u52a0\u3048\u308b\u3002"
    },
    "ko": {
      "name": "\ubc14\uc774\uc62c\ub81b \ub9c8\ub140",
      "effect": "\uc774 \uce74\ub4dc\uac00 \uc804\ud22c\uc5d0 \uc758\ud574 \ud30c\uad34\ub418\uc5b4 \ubb18\uc9c0\ub85c \ubcf4\ub0b4\uc84c\uc744 \ub54c, \uc790\uc2e0\uc758 \ub371\uc5d0\uc11c \uc218\ube44\ub825 1500 \uc774\ud558\uc758 \uc2dd\ubb3c\uc871 \ubaac\uc2a4\ud130 1\uc7a5\uc744 \ud328\uc5d0 \ub354\ud55c\ub2e4."
    }
  },
  "cardType": "monster",
  "attribute": "dark",
  "type": "spellcaster",
  "classifications": [
    "effect"
  ],
  "level": 4,
  "atk": 1100,
  "def": 1200,
  "passwords": [
    "62379337"
  ],
  "images": [
    {
      "id": "08cc4af9-2152-4806-a55b-0b9c953dda06",
      "password": "62379337",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/62379337.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/62379337.jpg"
    }
  ],
  "sets": [
    "59061cea-ab88-4396-90d9-8a3f145880e3",
    "59061cea-ab88-4396-90d9-8a3f145880e3",
    "59061cea-ab88-4396-90d9-8a3f145880e3",
    "59061cea-ab88-4396-90d9-8a3f145880e3",
    "59061cea-ab88-4396-90d9-8a3f145880e3",
    "59061cea-ab88-4396-90d9-8a3f145880e3",
    "59061cea-ab88-4396-90d9-8a3f145880e3",
    "59061cea-ab88-4396-90d9-8a3f145880e3",
    "59061cea-ab88-4396-90d9-8a3f145880e3",
    "59061cea-ab88-4396-90d9-8a3f145880e3",
    "fd69a0af-695d-486a-98b4-8f0e8e28f87a",
    "fd69a0af-695d-486a-98b4-8f0e8e28f87a",
    "fd69a0af-695d-486a-98b4-8f0e8e28f87a",
    "fd69a0af-695d-486a-98b4-8f0e8e28f87a",
    "fd69a0af-695d-486a-98b4-8f0e8e28f87a",
    "fd69a0af-695d-486a-98b4-8f0e8e28f87a",
    "1c07358e-b366-401b-8ca8-eef68dce3768",
    "2ff0c7b2-4be6-4d10-9309-547817fb34e3",
    "3c17174c-c620-4645-8ac4-36a0dad47d2c",
    "81645ce2-c736-49e8-91df-1d5ff08c9b45"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited",
      "currentLegality": "unlimited"
    },
    "ocg": {
      "current": "unlimited",
      "currentLegality": "unlimited"
    },
    "genesys": {
      "current": "unlimited",
      "currentLegality": "unlimited",
      "currentPoints": 0
    }
  },
  "masterDuel": {
    "rarity": "n",
    "craftable": true
  },
  "duelLinks": {
    "rarity": "sr"
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Violet Witch",
        "id": 42149
      }
    ],
    "dbID": 8088,
    "ygoprodeck": {
      "id": 62379337,
      "name": "violet-witch-5274"
    },
    "yamlyugiID": 62379337
  },
  "series": []
}

=== matt-roz/YGOJSON/cards/42fc7e16-14f5-4067-b021-afa395d4e9b3.json
{
  "$schema": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/card.json",
  "id": "42fc7e16-14f5-4067-b021-afa395d4e9b3",
  "text": {
    "en": {
      "name": "Satellarknight Sirius",
      "effect": "If this card is Summoned: You can target 5 \"tellarknight\" monsters in your Graveyard; shuffle all 5 into the Deck, then draw 1 card. You can only use this effect of \"Satellarknight Sirius\" once per turn."
    },
    "fr": {
      "name": "Satellchevalier Sirius",
      "effect": "Si cette carte est Invoqu\u00e9e : vous pouvez cibler 5 monstres \"tellchevalier\" dans votre Cimeti\u00e8re ; m\u00e9langez-les tous les 5 dans le Deck, puis piochez 1 carte. Vous ne pouvez utiliser cet effet de \"Satellchevalier Sirius\" qu'une fois par tour."
    },
    "de": {
      "name": "Fixsternritter Sirius",
      "effect": "Falls diese Karte beschworen wird: Du kannst 5 \u201eSternritter\u201c-Monster in deinem Friedhof w\u00e4hlen; mische alle 5 ins Deck, dann ziehe 1 Karte. Du kannst diesen Effekt von \u201eFixsternritter Sirius\u201c nur einmal pro Spielzug verwenden."
    },
    "it": {
      "name": "Satellcavaliere Sirio",
      "effect": "Se questa carta viene Evocata: puoi scegliere come bersaglio 5 mostri \"tellcavaliere\" nel tuo Cimitero; mischiali tutti e 5 nel Deck, poi pesca 1 carta. Puoi utilizzare questo effetto di \"Satellcavaliere Sirio\" una sola volta per turno."
    },
    "pt": {
      "name": "Cavaleirost\u00e9lite Sirius",
      "effect": "Se este card for Invocado: voc\u00ea pode escolher 5 monstros \"Cavaleirost\" no seu Cemit\u00e9rio; embaralhe todos os 5 no Deck e, depois, compre 1 card. Voc\u00ea s\u00f3 pode usar este efeito de \"Cavaleirost\u00e9lite Sirius\" uma vez por turno."
    },
    "es": {
      "name": "Satelcaballero Sirio",
      "effect": "Si esta carta es Invocada: puedes seleccionar 5 monstruos \"telcaballero\" en tu Cementerio; baraja los 5 al Deck, y despu\u00e9s roba 1 carta. S\u00f3lo puedes usar este efecto de \"Satelcaballero Sirio\" una vez por turno."
    },
    "ja": {
      "name": "\u661f\u56e0\u58eb \u30b7\u30ea\u30a6\u30b9",
      "effect": "\u300c\u661f\u56e0\u58eb \u30b7\u30ea\u30a6\u30b9\u300d\u306e\u52b9\u679c\u306f\uff11\u30bf\u30fc\u30f3\u306b\uff11\u5ea6\u3057\u304b\u4f7f\u7528\u3067\u304d\u306a\u3044\u3002\u2460\uff1a\u3053\u306e\u30ab\u30fc\u30c9\u304c\u53ec\u559a\u30fb\u53cd\u8ee2\u53ec\u559a\u30fb\u7279\u6b8a\u53ec\u559a\u306b\u6210\u529f\u3057\u305f\u5834\u5408\u3001\u81ea\u5206\u306e\u5893\u5730\u306e\u300c\u30c6\u30e9\u30ca\u30a4\u30c8\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\uff15\u4f53\u3092\u5bfe\u8c61\u3068\u3057\u3066\u767a\u52d5\u3067\u304d\u308b\u3002\u305d\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\uff15\u4f53\u3092\u30c7\u30c3\u30ad\u306b\u623b\u3057\u3066\u30b7\u30e3\u30c3\u30d5\u30eb\u3059\u308b\u3002\u305d\u306e\u5f8c\u3001\u81ea\u5206\u306f\u30c7\u30c3\u30ad\u304b\u3089\uff11\u679a\u30c9\u30ed\u30fc\u3059\u308b\u3002"
    },
    "ko": {
      "name": "\uc0ac\ud14c\ub77c\ub098\uc774\ud2b8 \uc2dc\ub9ac\uc6b0\uc2a4",
      "effect": "\"\uc0ac\ud14c\ub77c\ub098\uc774\ud2b8 \uc2dc\ub9ac\uc6b0\uc2a4\"\uc758 \ud6a8\uacfc\ub294 1\ud134\uc5d0 1\ubc88\ubc16\uc5d0 \uc0ac\uc6a9\ud560 \uc218 \uc5c6\ub2e4. \u2460 : \uc774 \uce74\ub4dc\uac00 \uc77c\ubc18 \uc18c\ud658 / \ubc18\uc804 \uc18c\ud658 / \ud2b9\uc218 \uc18c\ud658\uc5d0 \uc131\uacf5\ud588\uc744 \uacbd\uc6b0, \uc790\uc2e0 \ubb18\uc9c0\uc758 \"\ud14c\ub77c\ub098\uc774\ud2b8\" \ubaac\uc2a4\ud130 5\uc7a5\uc744 \ub300\uc0c1\uc73c\ub85c \ud558\uace0 \ubc1c\ub3d9\ud560 \uc218 \uc788\ub2e4. \uadf8 \ubaac\uc2a4\ud130 5\uc7a5\uc744 \ub371\uc73c\ub85c \ub418\ub3cc\ub9ac\uace0 \uc154\ud50c\ud55c\ub2e4. \uadf8 \ud6c4, \uc790\uc2e0\uc740 \ub371\uc5d0\uc11c 1\uc7a5 \ub4dc\ub85c\uc6b0\ud55c\ub2e4."
    },
    "zh-CN": {
      "name": "\u536b\u661f\u9a91\u58eb \u5927\u72ac\u897f\u5229\u4e4c\u65af",
      "effect": "\u6b64\u5361\u540d\u7684\u6548\u679c\uff11\u56de\u5408\u4ec5\u53ef\u4f7f\u7528\uff11\u6b21\u3002\u2460\uff1a\u6b64\u5361\u53ec\u5524\u30fb\u53cd\u8f6c\u53ec\u5524\u30fb\u7279\u6b8a\u53ec\u5524\u6210\u529f\u7684\u60c5\u51b5\u4e0b\uff0c\u4ee5\u81ea\u5df1\u5893\u5730\u7684\uff15\u53ea\u201c\u661f\u9a91\u58eb\u201d\u602a\u517d\u4e3a\u5bf9\u8c61\u53ef\u4ee5\u53d1\u52a8\u3002\u5c06\u8be5\uff15\u53ea\u602a\u517d\u653e\u56de\u724c\u7ec4\u6d17\u724c\u3002\u7136\u540e\u81ea\u5df1\u4ece\u724c\u7ec4\u62bd\uff11\u5f20\u3002"
    }
  },
  "cardType": "monster",
  "attribute": "light",
  "type": "warrior",
  "classifications": [
    "effect"
  ],
  "level": 4,
  "atk": 1600,
  "def": 900,
  "passwords": [
    "63274863"
  ],
  "images": [
    {
      "id": "3f728b10-1bdc-4561-915f-5d65adf90aed",
      "password": "63274863",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/63274863.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/63274863.jpg"
    }
  ],
  "sets": [
    "6651399f-45d7-4ccb-af30-3315ee938022",
    "6651399f-45d7-4ccb-af30-3315ee938022",
    "6651399f-45d7-4ccb-af30-3315ee938022",
    "6651399f-45d7-4ccb-af30-3315ee938022",
    "6651399f-45d7-4ccb-af30-3315ee938022",
    "6651399f-45d7-4ccb-af30-3315ee938022",
    "6651399f-45d7-4ccb-af30-3315ee938022",
    "6651399f-45d7-4ccb-af30-3315ee938022",
    "89f961c5-27a4-4062-868d-58c61f888c17",
    "89f961c5-27a4-4062-868d-58c61f888c17",
    "89f961c5-27a4-4062-868d-58c61f888c17",
    "89f961c5-27a4-4062-868d-58c61f888c17",
    "89f961c5-27a4-4062-868d-58c61f888c17",
    "89f961c5-27a4-4062-868d-58c61f888c17",
    "5fe0dd43-8998-484e-aa72-9bdf05e012f2",
    "0aa19b78-a439-4dee-bdb5-8d8a4dbc9338",
    "9a9b4279-b7af-4158-896b-d7cd460b306c",
    "a18d25e1-cb35-4f3c-bbed-ea0a0500e8ba",
    "ec0c36ab-8f25-4e05-9dd5-34bb55c90455"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited",
      "currentLegality": "unlimited"
    },
    "ocg": {
      "current": "unlimited",
      "currentLegality": "unlimited"
    },
    "genesys": {
      "current": "unlimited",
      "currentLegality": "unlimited",
      "currentPoints": 0
    }
  },
  "masterDuel": {
    "rarity": "r",
    "craftable": true
  },
  "duelLinks": {
    "rarity": "n"
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Satellarknight Sirius",
        "id": 308667
      }
    ],
    "dbID": 11359,
    "ygoprodeck": {
      "id": 63274863,
      "name": "satellarknight-sirius-5346"
    },
    "yamlyugiID": 63274863
  },
  "series": [
    "5cd82853-817d-4dbb-aee4-81fb23ac4457",
    "23c5e25f-7088-48de-a181-87784888b4f2"
  ]
}
