=== matt-roz/YGOJSON/schema/v1/card.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/card.json",
  "title": "Card",
  "description": "A logical Yu-Gi-Oh card (as opposed to a physical card, of which belongs to a set).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "text",
    "cardType",
    "passwords",
    "images",
    "sets",
    "legality",
    "externalIDs",
    "series"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/card.json"
    },
    "id": {
      "description": "The UUID of this card. The name of the card's file should be this UUID.",
      "type": "string",
      "format": "uuid"
    },
    "text": {
      "description": "A map of languages to textual card information.",
      "type": "object",
      "propertyNames": {
        "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/language.json"
      },
      "additionalProperties": {
        "description": "Textual information on the card.",
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "description": "The name of the card.",
            "type": "string"
          },
          "effect": {
            "description": "All text in the main text box of the card. (Normal monster flavor also goes here, despite the name.) Null if the card's text is unknown or untranslated.",
            "type": "string"
          },
          "pendulumEffect": {
            "description": "All text in the pendulum text box of the card. Only appears on pendulum cards.",
            "type": "string"
          },
          "official": {
            "description": "Is this translation official or not? Default is true.",
            "type": "boolean"
          }
        }
      }
    },
    "cardType": {
      "description": "The broadest category of card (monster, spell, trap, etc.)",
      "enum": [
        "monster",
        "spell",
        "trap",
        "token",
        "skill"
      ]
    },
    "attribute": {
      "description": "The monster attribute. Only appears on monster or token cards.",
      "enum": [
        "light",
        "dark",
        "fire",
        "water",
        "wind",
        "earth",
        "divine"
      ]
    },
    "monsterCardTypes": {
      "description": "What summoning types this card is, if any. Only appears on monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "ritual",
          "fusion",
          "synchro",
          "xyz",
          "pendulum",
          "link"
        ]
      }
    },
    "type": {
      "description": "The race of monster. Only appears on monster or token cards.",
      "enum": [
        "beastwarrior",
        "zombie",
        "fiend",
        "dinosaur",
        "dragon",
        "beast",
        "illusion",
        "insect",
        "wingedbeast",
        "warrior",
        "seaserpent",
        "aqua",
        "pyro",
        "thunder",
        "spellcaster",
        "plant",
        "rock",
        "reptile",
        "fairy",
        "fish",
        "machine",
        "divinebeast",
        "psychic",
        "creatorgod",
        "wyrm",
        "cyberse"
      ]
    },
    "classifications": {
      "description": "Any non-type, non-ability categories appearing on the type line (effect, normal, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "normal",
          "effect",
          "pendulum",
          "tuner",
          "specialsummon"
        ]
      }
    },
    "abilities": {
      "description": "Any non-type, ability categories appearing on the type line (toon, spirit, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "toon",
          "spirit",
          "union",
          "gemini",
          "flip"
        ]
      }
    },
    "level": {
      "description": "The level of this card. Only appears on non-link, non-xyz monster or token cards.",
      "type": "integer"
    },
    "rank": {
      "description": "The rank of this card. Only appears on xyz monster cards.",
      "type": "integer"
    },
    "atk": {
      "description": "The ATK of the card. Either a number, or '?'. Only appears on monster or token cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "def": {
      "description": "The DEF of the card. Either a number, or '?'. Only appears on non-link monster cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "scale": {
      "description": "The pendulum scale. Only appears on pendulum monster cards.",
      "type": "integer"
    },
    "linkArrows": {
      "description": "The link arrows on this card. Only appears on link monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "topleft",
          "topcenter",
          "topright",
          "middleleft",
          "middleright",
          "bottomleft",
          "bottomcenter",
          "bottomright"
        ]
      }
    },
    "subcategory": {
      "description": "The type of spell/trap card this is. Only appears on spell/trap cards.",
      "enum": [
        "normal",
        "continuous",
        "equip",
        "quickplay",
        "field",
        "ritual",
        "counter"
      ]
    },
    "character": {
      "description": "The character a skill card corresponds to. Only present in skill cards.",
      "type": "string"
    },
    "skillType": {
      "description": "The card type a skill card is. Only present in skill cards.",
      "type": "string"
    },
    "passwords": {
      "description": "All official passwords given for the card.",
      "type": "array",
      "items": {
        "description": "A password, as printed on the card.",
        "type": "string",
        "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
      }
    },
    "images": {
      "description": "Card images, one per art variant. These images are generic to the card, generated automatically and in English, rather than being the image of a specific printing.",
      "type": "array",
      "items": {
        "description": "An image for a specific art treatment of a card.",
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "description": "The UUID of this art treatment. Used to refer to specific art treatments from specific printings.",
            "type": "string",
            "format": "uuid"
          },
          "password": {
            "description": "The password this art is given to. Some cards have multiple passwords, one per art. Some cards have multiple arts with the same password. And some have both going on. Not present if the card's password is currently unknown, or the card has no passwords, such as is the case for tokens.",
            "type": "string",
            "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
          },
          "art": {
            "description": "An art crop of this card.",
            "type": "string",
            "format": "uri"
          },
          "card": {
            "description": "An image of this card.",
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "sets": {
      "description": "A list of sets each card was (or will be) found in. Look up these UUIDs in the set JSON for printing information.",
      "type": "array",
      "items": {
        "description": "A UUID of the set this card appears in.",
        "type": "string",
        "format": "uuid"
      }
    },
    "illegal": {
      "description": "If true, then this card is illegal, and will not have any legality history. Never set for cards that are not game pieces, such as tokens.",
      "type": "boolean"
    },
    "legality": {
      "description": "A mapping of formats to legalities.",
      "type": "object",
      "propertyNames": {
        "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/format.json"
      },
      "additionalProperties": {
        "description": "Legality information for this format. Never set for cards that are illegal or are not game pieces (such as tokens).",
        "type": "object",
        "required": [
          "current"
        ],
        "properties": {
          "current": {
            "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/legality.json",
            "description": "The current legality of this card. Deprecated; use 'currentLegality' instead.",
            "deprecated": true
          },
          "currentLegality": {
            "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/legality.json",
            "description": "The current legality of this card. Use this to avoid reading the legality history, or use this when the legality history is unknown/empty."
          },
          "currentPoints": {
            "description": "The current point cost of this card, for formats that use points. Use this to avoid reading the legality history, or use this when the legality history is unknown/empty.",
            "type": "number"
          },
          "history": {
            "description": "The legality history for this card. Only present if this history is known, but may be empty even if known, in the case of cards whose legality has never changed.",
            "type": "array",
            "items": {
              "description": "A record of a change in legality.",
              "type": "object",
              "required": [
                "legality",
                "date"
              ],
              "properties": {
                "legality": {
                  "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/legality.json",
                  "description": "What the legality was changed to."
                },
                "points": {
                  "description": "What the point cost was changed to, for formats that use points.",
                  "type": "number"
                },
                "date": {
                  "description": "The date of the change.",
                  "type": "string",
                  "format": "date"
                }
              }
            }
          }
        }
      }
    },
    "masterDuel": {
      "description": "Any Master Duel specific information. Only present if this card is in Master Duel.",
      "type": "object",
      "required": [
        "rarity",
        "craftable"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        },
        "craftable": {
          "description": "Is this card craftable using dust?",
          "type": "boolean"
        }
      }
    },
    "duelLinks": {
      "description": "Any Duel Links specific information. Only present if this card is in Duel Links.",
      "type": "object",
      "required": [
        "rarity"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        }
      }
    },
    "externalIDs": {
      "description": "IDs and other information, to access this card from various other sites.",
      "type": "object",
      "required": [],
      "properties": {
        "yugipedia": {
          "description": "Information for Yugipedia. This array is usually 1 element long, but some cards, like Polymerizarion or the God Cards, have multiple Yugipedia pages that represent the same card.",
          "type": "array",
          "items": {
            "description": "A Yugipedia page.",
            "type": "object",
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "name": {
                "description": "The page name for this card.",
                "type": "string"
              },
              "id": {
                "description": "The internal wiki ID for the page for this card.",
                "type": "integer"
              }
            }
          }
        },
        "dbID": {
          "description": "The CID this card has on db.yugioh-card.com.",
          "type": "integer"
        },
        "ygoprodeck": {
          "description": "Information for YGOProDeck, if available",
          "type": "object",
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "name": {
              "description": "The slug for YGOProDeck you can use after 'ygoprodeck.com/card/' to get the card's page.",
              "type": "string"
            },
            "id": {
              "description": "The internal ID in YGOProDeck for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
              "type": "integer"
            }
          }
        },
        "yugiohpricesName": {
          "description": "The slug for YugiohPrices and YugiohTopDecks you can use to get the card's page. Deprecated; YugiohPrices no longer exists.",
          "type": "string",
          "deprecated": true
        },
        "yamlyugiID": {
          "description": "The internal ID in YamlYugi for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
          "type": "integer"
        }
      }
    },
    "errata": {
      "description": "Present only if this card has recieved errata. Details how the card has changed over time. Does not cover format legality information.",
      "type": "object",
      "required": [
        "original",
        "history"
      ],
      "properties": {
        "original": {
          "description": "What is the original state of the card, as first printed? A subset of the card json, with only changed properties present.",
          "type": "object"
        },
        "history": {
          "description": "The change history.",
          "type": "array",
          "items": {
            "description": "A change.",
            "type": "object",
            "required": [
              "date",
              "changes",
              "official"
            ],
            "properties": {
              "date": {
                "description": "The date of the change.",
                "type": "string",
                "format": "date"
              },
              "changes": {
                "description": "What changed with this errata. A subset of the card json, with only changed properties present.",
                "type": "object"
              },
              "official": {
                "description": "Was this change official? Unofficial changes may occur in the case of a temporary name/text beging updated when a card officially comes out in that locale.",
                "type": "boolean"
              }
            }
          }
        }
      }
    },
    "series": {
      "description": "Any series or archetypes this card is a part of.",
      "type": "array",
      "items": {
        "description": "The UUID of the series. Look it up in the series JSON.",
        "type": "string",
        "format": "uuid"
      }
    }
  }
}

=== matt-roz/YGOJSON/cards/b2891c71-fd19-49f3-9a09-d877451c3783.json
{
  "$schema": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/card.json",
  "id": "b2891c71-fd19-49f3-9a09-d877451c3783",
  "text": {
    "en": {
      "name": "Cyberse Sage",
      "effect": "You can Ritual Summon this card with \"Cynet Ritual\". During your Main Phase: You can Fusion Summon 1 Fusion Monster from your Extra Deck, by banishing materials mentioned on it from your field or GY, including a Cyberse monster. If this card is sent to the GY as Synchro Material: You can target 1 Cyberse monster or 1 Ritual Spell in your GY; add it to your hand. You can only use each effect of \"Cyberse Sage\" once per turn."
    },
    "fr": {
      "name": "Sage Cyberse",
      "effect": "Vous pouvez Invoquer Rituellement cette carte avec \"Cynet Rituel\". Durant votre Main Phase : vous pouvez Invoquer par Fusion 1 Monstre Fusion depuis votre Extra Deck, en bannissant les Mat\u00e9riels mentionn\u00e9s sur celui-ci (un monstre Cyberse inclus) depuis votre Terrain ou Cimeti\u00e8re. Si cette carte est envoy\u00e9e au Cimeti\u00e8re comme Mat\u00e9riel Synchro : vous pouvez cibler 1 monstre Cyberse ou 1 Magie Rituelle dans votre Cimeti\u00e8re ; ajoutez-le \u00e0 votre main. Vous ne pouvez utiliser chaque effet de \"Sage Cyberse\" qu'une fois par tour."
    },
    "de": {
      "name": "Cyberse-Weise",
      "effect": "Du kannst diese Karte mit \u201eCynet-Ritual\u201c als Ritualbeschw\u00f6rung beschw\u00f6ren. W\u00e4hrend deiner Main Phase: Du kannst 1 Fusionsmonster als Fusionsbeschw\u00f6rung von deinem Extra Deck beschw\u00f6ren, indem du das auf ihm erw\u00e4hnte Material von deiner Spielfeldseite oder deinem Friedhof verbannst, darunter ein Cyberse-Monster. Falls diese Karte als Synchromaterial auf den Friedhof gelegt wird: Du kannst 1 Cyberse-Monster oder 1 Ritualzauber in deinem Friedhof w\u00e4hlen; f\u00fcge es oder ihn deiner Hand hinzu. Du kannst jeden Effekt von \u201eCyberse-Weise\u201c nur einmal pro Spielzug verwenden."
    },
    "it": {
      "name": "Saggia Cyberso",
      "effect": "Puoi Evocare tramite Rituale questa carta con \"Cynet Rituale\". Durante la tua Main Phase: puoi Evocare tramite Fusione 1 Mostro Fusione dal tuo Extra Deck, bandendo i materiali menzionati su di esso dal tuo Terreno o Cimitero, compreso un mostro Cyberso. Se questa carta viene mandata al Cimitero come Materiale Synchro: puoi scegliere come bersaglio 1 mostro Cyberso o 1 Magia Rituale nel tuo Cimitero; aggiungila alla tua mano. Puoi utilizzare ogni effetto di \"Saggia Cyberso\" una sola volta per turno."
    },
    "pt": {
      "name": "S\u00e1bia Ciberso",
      "effect": "Voc\u00ea pode Invocar este card por Invoca\u00e7\u00e3o-Ritual com \"Cinet Ritual\". Durante sua Fase Principal: voc\u00ea pode Invocar por Invoca\u00e7\u00e3o-Fus\u00e3o 1 Monstro de Fus\u00e3o do seu Deck Adicional, ao banir mat\u00e9rias mencionadas nele do seu campo ou Cemit\u00e9rio, incluindo um monstro Ciberso. Se este card for enviado para o Cemit\u00e9rio como Mat\u00e9ria Sincro: voc\u00ea pode escolher 1 monstro Ciberso ou 1 Magia de Ritual no seu Cemit\u00e9rio; adicione-o \u00e0 sua m\u00e3o. Voc\u00ea s\u00f3 pode usar cada efeito de \"S\u00e1bia Ciberso\" uma vez por turno."
    },
    "es": {
      "name": "Sabia Ciberso",
      "effect": "Puedes Invocar esta carta por Ritual con \"Cinet-Ritual\". Durante tu Main Phase: puedes Invocar por Fusi\u00f3n 1 Monstruo de Fusi\u00f3n desde tu Deck Extra, desterrando de tu Campo o Cementerio materiales mencionados en \u00e9l, incluyendo un monstruo Ciberso. Si esta carta es mandada al Cementerio como Material de Sincron\u00eda: puedes seleccionar 1 monstruo Ciberso o 1 M\u00e1gica de Ritual en tu Cementerio; a\u00f1\u00e1delo a tu mano. S\u00f3lo puedes usar cada efecto de \"Sabia Ciberso\" una vez por turno."
    },
    "ja": {
      "name": "\u30b5\u30a4\u30d0\u30fc\u30b9\u30fb\u30bb\u30a4\u30b8",
      "effect": "\u300c\u30b5\u30a4\u30d0\u30cd\u30c3\u30c8\u30fb\u30ea\u30c1\u30e5\u30fc\u30a2\u30eb\u300d\u306b\u3088\u308a\u964d\u81e8\u3002\u3053\u306e\u30ab\u30fc\u30c9\u540d\u306e\u2460\u2461\u306e\u52b9\u679c\u306f\u305d\u308c\u305e\u308c\uff11\u30bf\u30fc\u30f3\u306b\uff11\u5ea6\u3057\u304b\u4f7f\u7528\u3067\u304d\u306a\u3044\u3002\u2460\uff1a\u81ea\u5206\u30e1\u30a4\u30f3\u30d5\u30a7\u30a4\u30ba\u306b\u767a\u52d5\u3067\u304d\u308b\u3002\u81ea\u5206\u306e\u30d5\u30a3\u30fc\u30eb\u30c9\u30fb\u5893\u5730\u304b\u3089\u3001\u878d\u5408\u30e2\u30f3\u30b9\u30bf\u30fc\u30ab\u30fc\u30c9\u306b\u3088\u3063\u3066\u6c7a\u3081\u3089\u308c\u305f\u3001\u30b5\u30a4\u30d0\u30fc\u30b9\u65cf\u30e2\u30f3\u30b9\u30bf\u30fc\u3092\u542b\u3080\u878d\u5408\u7d20\u6750\u30e2\u30f3\u30b9\u30bf\u30fc\u3092\u9664\u5916\u3057\u3001\u305d\u306e\u878d\u5408\u30e2\u30f3\u30b9\u30bf\u30fc\uff11\u4f53\u3092\uff25\uff38\u30c7\u30c3\u30ad\u304b\u3089\u878d\u5408\u53ec\u559a\u3059\u308b\u3002\u2461\uff1a\u3053\u306e\u30ab\u30fc\u30c9\u304c\uff33\u7d20\u6750\u3068\u3057\u3066\u5893\u5730\u3078\u9001\u3089\u308c\u305f\u5834\u5408\u3001\u81ea\u5206\u306e\u5893\u5730\u306e\u3001\u30b5\u30a4\u30d0\u30fc\u30b9\u65cf\u30e2\u30f3\u30b9\u30bf\u30fc\uff11\u4f53\u307e\u305f\u306f\u5100\u5f0f\u9b54\u6cd5\u30ab\u30fc\u30c9\uff11\u679a\u3092\u5bfe\u8c61\u3068\u3057\u3066\u767a\u52d5\u3067\u304d\u308b\u3002\u305d\u306e\u30ab\u30fc\u30c9\u3092\u624b\u672d\u306b\u52a0\u3048\u308b\u3002"
    },
    "ko": {
      "name": "\uc0ac\uc774\ubc84\uc2a4 \uc138\uc774\uc9c0",
      "effect": "\"\uc0ac\uc774\ubc14\ub137 \ub9ac\uce04\uc5bc\"\uc5d0 \uc758\ud574 \uc758\uc2dd \uc18c\ud658. \uc774 \uce74\ub4dc\uba85\uc758 \u2460\u2461\uc758 \ud6a8\uacfc\ub294 \uac01\uac01 1\ud134\uc5d0 1\ubc88\ubc16\uc5d0 \uc0ac\uc6a9\ud560 \uc218 \uc5c6\ub2e4. \u2460: \uc790\uc2e0 \uba54\uc778 \ud398\uc774\uc988\uc5d0 \ubc1c\ub3d9\ud560 \uc218 \uc788\ub2e4. \uc790\uc2e0\uc758 \ud544\ub4dc / \ubb18\uc9c0\uc5d0\uc11c, \uc735\ud569 \ubaac\uc2a4\ud130 \uce74\ub4dc\uc5d0 \uae30\uc7ac\ub41c, \uc0ac\uc774\ubc84\uc2a4\uc871 \ubaac\uc2a4\ud130\ub97c \ud3ec\ud568\ud558\ub294 \uc735\ud569 \uc18c\uc7ac \ubaac\uc2a4\ud130\ub97c \uc81c\uc678\ud558\uace0, \uadf8 \uc735\ud569 \ubaac\uc2a4\ud130 1\uc7a5\uc744 \uc5d1\uc2a4\ud2b8\ub77c \ub371\uc5d0\uc11c \uc735\ud569 \uc18c\ud658\ud55c\ub2e4. \u2461: \uc774 \uce74\ub4dc\uac00 \uc2f1\ud06c\ub85c \uc18c\uc7ac\ub85c\uc11c \ubb18\uc9c0\ub85c \ubcf4\ub0b4\uc84c\uc744 \uacbd\uc6b0, \uc790\uc2e0 \ubb18\uc9c0\uc758, \uc0ac\uc774\ubc84\uc2a4\uc871 \ubaac\uc2a4\ud130 1\uc7a5 \ub610\ub294 \uc758\uc2dd \ub9c8\ubc95 \uce74\ub4dc 1\uc7a5\uc744 \ub300\uc0c1\uc73c\ub85c \ud558\uace0 \ubc1c\ub3d9\ud560 \uc218 \uc788\ub2e4. \uadf8 \uce74\ub4dc\ub97c \ud328\uc5d0 \ub123\ub294\ub2e4."
    },
    "zh-CN": {
      "name": "\u7535\u5b50\u754c\u4f4e\u8c03\u8d24\u8005",
      "effect": "\u4ee5\u201c\u7535\u8111\u7f51\u4eea\u5f0f\u201d\u964d\u4e34\u3002\u6b64\u5361\u540d\u7684\u2460\u2461\u6548\u679c\uff11\u56de\u5408\u4ec5\u53ef\u5404\u4f7f\u7528\uff11\u6b21\u3002\u2460\uff1a\u5728\u81ea\u5df1\u7684\u4e3b\u8981\u9636\u6bb5\u53ef\u4ee5\u53d1\u52a8\u3002\u4ece\u81ea\u5df1\u573a\u4e0a\u30fb\u5893\u5730\uff0c\u5c06\u7531\u878d\u5408\u602a\u517d\u5361\u51b3\u5b9a\u7684\u3001\u5305\u542b\u7535\u5b50\u754c\u65cf\u602a\u517d\u5728\u5185\u7684\u878d\u5408\u7d20\u6750\u602a\u517d\u9664\u5916\uff0c\u4ece\u989d\u5916\u724c\u7ec4\u5c06\uff11\u53ea\u8be5\u878d\u5408\u602a\u517d\u878d\u5408\u53ec\u5524\u3002\u2461\uff1a\u6b64\u5361\u4f5c\u4e3a\u540c\u6b65\u7d20\u6750\u88ab\u9001\u81f3\u5893\u5730\u7684\u60c5\u51b5\u4e0b\uff0c\u4ee5\u81ea\u5df1\u5893\u5730\u7684\uff11\u53ea\u7535\u5b50\u754c\u65cf\u602a\u517d\u6216\uff11\u5f20\u4eea\u5f0f\u9b54\u6cd5\u5361\u4e3a\u5bf9\u8c61\u53ef\u4ee5\u53d1\u52a8\u3002\u5c06\u8be5\u5361\u52a0\u5165\u624b\u724c\u3002"
    }
  },
  "cardType": "monster",
  "attribute": "dark",
  "monsterCardTypes": [
    "ritual"
  ],
  "type": "cyberse",
  "classifications": [
    "effect",
    "tuner"
  ],
  "level": 1,
  "atk": 0,
  "def": 0,
  "passwords": [
    "65037172"
  ],
  "images": [
    {
      "id": "825ac438-e17a-40e1-8c89-7e8cedeb9a3a",
      "password": "65037172",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/65037172.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/65037172.jpg"
    }
  ],
  "sets": [
    "111e56c0-647b-4971-9b1e-411b4b8413e2",
    "111e56c0-647b-4971-9b1e-411b4b8413e2",
    "111e56c0-647b-4971-9b1e-411b4b8413e2",
    "111e56c0-647b-4971-9b1e-411b4b8413e2",
    "111e56c0-647b-4971-9b1e-411b4b8413e2",
    "111e56c0-647b-4971-9b1e-411b4b8413e2",
    "111e56c0-647b-4971-9b1e-411b4b8413e2",
    "111e56c0-647b-4971-9b1e-411b4b8413e2",
    "6b51b0c5-edba-4322-8ede-176bc1efa365",
    "bab500ab-cf81-45ef-b280-b07ac122f02f",
    "4d054c20-1199-41f5-b17b-0018ec0d80da",
    "9cc3f5c9-585f-45c1-ab07-1881210ec071",
    "834688ec-e8ca-436f-8a52-8902aad38df7",
    "3302ac35-19ec-4ade-85ed-97e8cb4fb84b"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited",
      "currentLegality": "unlimited"
    },
    "ocg": {
      "current": "unlimited",
      "currentLegality": "unlimited"
    },
    "genesys": {
      "current": "unlimited",
      "currentLegality": "unlimited",
      "currentPoints": 0
    }
  },
  "masterDuel": {
    "rarity": "n",
    "craftable": true
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Cyberse Sage",
        "id": 714432
      }
    ],
    "dbID": 18496,
    "ygoprodeck": {
      "id": 65037172,
      "name": "cyberse-sage-13599"
    },
    "yamlyugiID": 65037172
  },
  "series": [
    "49bef392-a1bc-470d-a8df-5b07e181b196"
  ]
}
