=== matt-roz/YGOJSON/schema/v1/card.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/card.json",
  "title": "Card",
  "description": "A logical Yu-Gi-Oh card (as opposed to a physical card, of which belongs to a set).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "text",
    "cardType",
    "passwords",
    "images",
    "sets",
    "legality",
    "externalIDs",
    "series"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/card.json"
    },
    "id": {
      "description": "The UUID of this card. The name of the card's file should be this UUID.",
      "type": "string",
      "format": "uuid"
    },
    "text": {
      "description": "A map of languages to textual card information.",
      "type": "object",
      "propertyNames": {
        "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/language.json"
      },
      "additionalProperties": {
        "description": "Textual information on the card.",
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "description": "The name of the card.",
            "type": "string"
          },
          "effect": {
            "description": "All text in the main text box of the card. (Normal monster flavor also goes here, despite the name.) Null if the card's text is unknown or untranslated.",
            "type": "string"
          },
          "pendulumEffect": {
            "description": "All text in the pendulum text box of the card. Only appears on pendulum cards.",
            "type": "string"
          },
          "official": {
            "description": "Is this translation official or not? Default is true.",
            "type": "boolean"
          }
        }
      }
    },
    "cardType": {
      "description": "The broadest category of card (monster, spell, trap, etc.)",
      "enum": [
        "monster",
        "spell",
        "trap",
        "token",
        "skill"
      ]
    },
    "attribute": {
      "description": "The monster attribute. Only appears on monster or token cards.",
      "enum": [
        "light",
        "dark",
        "fire",
        "water",
        "wind",
        "earth",
        "divine"
      ]
    },
    "monsterCardTypes": {
      "description": "What summoning types this card is, if any. Only appears on monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "ritual",
          "fusion",
          "synchro",
          "xyz",
          "pendulum",
          "link"
        ]
      }
    },
    "type": {
      "description": "The race of monster. Only appears on monster or token cards.",
      "enum": [
        "beastwarrior",
        "zombie",
        "fiend",
        "dinosaur",
        "dragon",
        "beast",
        "illusion",
        "insect",
        "wingedbeast",
        "warrior",
        "seaserpent",
        "aqua",
        "pyro",
        "thunder",
        "spellcaster",
        "plant",
        "rock",
        "reptile",
        "fairy",
        "fish",
        "machine",
        "divinebeast",
        "psychic",
        "creatorgod",
        "wyrm",
        "cyberse"
      ]
    },
    "classifications": {
      "description": "Any non-type, non-ability categories appearing on the type line (effect, normal, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "normal",
          "effect",
          "pendulum",
          "tuner",
          "specialsummon"
        ]
      }
    },
    "abilities": {
      "description": "Any non-type, ability categories appearing on the type line (toon, spirit, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "toon",
          "spirit",
          "union",
          "gemini",
          "flip"
        ]
      }
    },
    "level": {
      "description": "The level of this card. Only appears on non-link, non-xyz monster or token cards.",
      "type": "integer"
    },
    "rank": {
      "description": "The rank of this card. Only appears on xyz monster cards.",
      "type": "integer"
    },
    "atk": {
      "description": "The ATK of the card. Either a number, or '?'. Only appears on monster or token cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "def": {
      "description": "The DEF of the card. Either a number, or '?'. Only appears on non-link monster cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "scale": {
      "description": "The pendulum scale. Only appears on pendulum monster cards.",
      "type": "integer"
    },
    "linkArrows": {
      "description": "The link arrows on this card. Only appears on link monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "topleft",
          "topcenter",
          "topright",
          "middleleft",
          "middleright",
          "bottomleft",
          "bottomcenter",
          "bottomright"
        ]
      }
    },
    "subcategory": {
      "description": "The type of spell/trap card this is. Only appears on spell/trap cards.",
      "enum": [
        "normal",
        "continuous",
        "equip",
        "quickplay",
        "field",
        "ritual",
        "counter"
      ]
    },
    "character": {
      "description": "The character a skill card corresponds to. Only present in skill cards.",
      "type": "string"
    },
    "skillType": {
      "description": "The card type a skill card is. Only present in skill cards.",
      "type": "string"
    },
    "passwords": {
      "description": "All official passwords given for the card.",
      "type": "array",
      "items": {
        "description": "A password, as printed on the card.",
        "type": "string",
        "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
      }
    },
    "images": {
      "description": "Card images, one per art variant. These images are generic to the card, generated automatically and in English, rather than being the image of a specific printing.",
      "type": "array",
      "items": {
        "description": "An image for a specific art treatment of a card.",
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "description": "The UUID of this art treatment. Used to refer to specific art treatments from specific printings.",
            "type": "string",
            "format": "uuid"
          },
          "password": {
            "description": "The password this art is given to. Some cards have multiple passwords, one per art. Some cards have multiple arts with the same password. And some have both going on. Not present if the card's password is currently unknown, or the card has no passwords, such as is the case for tokens.",
            "type": "string",
            "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
          },
          "art": {
            "description": "An art crop of this card.",
            "type": "string",
            "format": "uri"
          },
          "card": {
            "description": "An image of this card.",
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "sets": {
      "description": "A list of sets each card was (or will be) found in. Look up these UUIDs in the set JSON for printing information.",
      "type": "array",
      "items": {
        "description": "A UUID of the set this card appears in.",
        "type": "string",
        "format": "uuid"
      }
    },
    "illegal": {
      "description": "If true, then this card is illegal, and will not have any legality history. Never set for cards that are not game pieces, such as tokens.",
      "type": "boolean"
    },
    "legality": {
      "description": "A mapping of formats to legalities.",
      "type": "object",
      "propertyNames": {
        "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/format.json"
      },
      "additionalProperties": {
        "description": "Legality information for this format. Never set for cards that are illegal or are not game pieces (such as tokens).",
        "type": "object",
        "required": [
          "current"
        ],
        "properties": {
          "current": {
            "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/legality.json",
            "description": "The current legality of this card. Deprecated; use 'currentLegality' instead.",
            "deprecated": true
          },
          "currentLegality": {
            "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/legality.json",
            "description": "The current legality of this card. Use this to avoid reading the legality history, or use this when the legality history is unknown/empty."
          },
          "currentPoints": {
            "description": "The current point cost of this card, for formats that use points. Use this to avoid reading the legality history, or use this when the legality history is unknown/empty.",
            "type": "number"
          },
          "history": {
            "description": "The legality history for this card. Only present if this history is known, but may be empty even if known, in the case of cards whose legality has never changed.",
            "type": "array",
            "items": {
              "description": "A record of a change in legality.",
              "type": "object",
              "required": [
                "legality",
                "date"
              ],
              "properties": {
                "legality": {
                  "$ref": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/legality.json",
                  "description": "What the legality was changed to."
                },
                "points": {
                  "description": "What the point cost was changed to, for formats that use points.",
                  "type": "number"
                },
                "date": {
                  "description": "The date of the change.",
                  "type": "string",
                  "format": "date"
                }
              }
            }
          }
        }
      }
    },
    "masterDuel": {
      "description": "Any Master Duel specific information. Only present if this card is in Master Duel.",
      "type": "object",
      "required": [
        "rarity",
        "craftable"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        },
        "craftable": {
          "description": "Is this card craftable using dust?",
          "type": "boolean"
        }
      }
    },
    "duelLinks": {
      "description": "Any Duel Links specific information. Only present if this card is in Duel Links.",
      "type": "object",
      "required": [
        "rarity"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        }
      }
    },
    "externalIDs": {
      "description": "IDs and other information, to access this card from various other sites.",
      "type": "object",
      "required": [],
      "properties": {
        "yugipedia": {
          "description": "Information for Yugipedia. This array is usually 1 element long, but some cards, like Polymerizarion or the God Cards, have multiple Yugipedia pages that represent the same card.",
          "type": "array",
          "items": {
            "description": "A Yugipedia page.",
            "type": "object",
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "name": {
                "description": "The page name for this card.",
                "type": "string"
              },
              "id": {
                "description": "The internal wiki ID for the page for this card.",
                "type": "integer"
              }
            }
          }
        },
        "dbID": {
          "description": "The CID this card has on db.yugioh-card.com.",
          "type": "integer"
        },
        "ygoprodeck": {
          "description": "Information for YGOProDeck, if available",
          "type": "object",
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "name": {
              "description": "The slug for YGOProDeck you can use after 'ygoprodeck.com/card/' to get the card's page.",
              "type": "string"
            },
            "id": {
              "description": "The internal ID in YGOProDeck for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
              "type": "integer"
            }
          }
        },
        "yugiohpricesName": {
          "description": "The slug for YugiohPrices and YugiohTopDecks you can use to get the card's page. Deprecated; YugiohPrices no longer exists.",
          "type": "string",
          "deprecated": true
        },
        "yamlyugiID": {
          "description": "The internal ID in YamlYugi for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
          "type": "integer"
        }
      }
    },
    "errata": {
      "description": "Present only if this card has recieved errata. Details how the card has changed over time. Does not cover format legality information.",
      "type": "object",
      "required": [
        "original",
        "history"
      ],
      "properties": {
        "original": {
          "description": "What is the original state of the card, as first printed? A subset of the card json, with only changed properties present.",
          "type": "object"
        },
        "history": {
          "description": "The change history.",
          "type": "array",
          "items": {
            "description": "A change.",
            "type": "object",
            "required": [
              "date",
              "changes",
              "official"
            ],
            "properties": {
              "date": {
                "description": "The date of the change.",
                "type": "string",
                "format": "date"
              },
              "changes": {
                "description": "What changed with this errata. A subset of the card json, with only changed properties present.",
                "type": "object"
              },
              "official": {
                "description": "Was this change official? Unofficial changes may occur in the case of a temporary name/text beging updated when a card officially comes out in that locale.",
                "type": "boolean"
              }
            }
          }
        }
      }
    },
    "series": {
      "description": "Any series or archetypes this card is a part of.",
      "type": "array",
      "items": {
        "description": "The UUID of the series. Look it up in the series JSON.",
        "type": "string",
        "format": "uuid"
      }
    }
  }
}

=== matt-roz/YGOJSON/cards/98d207eb-9d03-401c-95ee-203e39db0a0b.json
{
  "$schema": "https://raw.githubusercontent.com/matt-roz/YGOJSON/main/schema/v1/card.json",
  "id": "98d207eb-9d03-401c-95ee-203e39db0a0b",
  "text": {
    "en": {
      "name": "Vaylantz Wakening - Solo Activation",
      "effect": "Place 1 \"Vaylantz\" Pendulum Monster from your Deck in your Pendulum Zone. If a card is in a Field Zone: You can banish this card from your GY, then target 1 \"Vaylantz\" monster in your Main Monster Zone; move that monster you control to an adjacent (horizontal) Monster Zone. You can only use each effect of \"Vaylantz Wakening - Solo Activation\" once per turn."
    },
    "fr": {
      "name": "R\u00e9veil Vaylantz - Activation Solo",
      "effect": "Placez 1 Monstre Pendule \"Vaylantz\" depuis votre Deck dans votre Zone Pendule. Si une carte est dans une Zone Terrain : vous pouvez bannir cette carte depuis votre Cimeti\u00e8re, puis ciblez 1 monstre \"Vaylantz\" dans votre Zone Monstre Main ; d\u00e9placez le monstre que vous contr\u00f4lez dans une Zone Monstre (horizontale) adjacente. Vous ne pouvez utiliser chaque effet de \"R\u00e9veil Vaylantz - Activation Solo\" qu'une fois par tour."
    },
    "de": {
      "name": "Vaylantz-Erwachen - Solo-Aktivierung",
      "effect": "Lege 1 \u201eVaylantz\u201c-Pendelmonster von deinem Deck in deine Pendelzone. Falls eine Karte in einer Spielfeldzone liegt: Du kannst diese Karte von deinem Friedhof verbannen und dann 1 \u201eVaylantz\u201c-Monster in deiner Main-Monsterzone w\u00e4hlen; bewege jenes Monster, das du kontrollierst, in eine (waagerecht) benachbarte Monsterzone. Du kannst jeden Effekt von \u201eVaylantz-Erwachen - Solo-Aktivierung\u201c nur einmal pro Spielzug verwenden."
    },
    "it": {
      "name": "Risveglio Vaylantz - Attivazione Solitaria",
      "effect": "Metti 1 Mostro Pendulum \"Vaylantz\" dal tuo Deck nella tua Zona Pendulum. Se una carta \u00e8 in una Zona Terreno: puoi bandire questa carta dal tuo Cimitero, poi scegliere come bersaglio 1 mostro \"Vaylantz\" nella tua Zona Mostri Main; sposta quel mostro che controlli in una Zona Mostri adiacente (orizzontalmente). Puoi utilizzare ogni effetto di \"Risveglio Vaylantz - Attivazione Solitaria\" una sola volta per turno."
    },
    "pt": {
      "name": "Despertar Vaylantz - Ativa\u00e7\u00e3o Individual",
      "effect": "Coloque 1 Monstro P\u00eandulo \"Vaylantz\" do seu Deck na sua Zona de P\u00eandulo. Se um card estiver em uma Zona do Campo: voc\u00ea pode banir este card do seu Cemit\u00e9rio e, depois, escolha 1 monstro \"Vaylantz\" na sua Zona de Monstros Principal; mova esse monstro que voc\u00ea controla para uma Zona de Monstros adjacente (horizontal). Voc\u00ea s\u00f3 pode usar cada efeito de \"Despertar Vaylantz - Ativa\u00e7\u00e3o Individual\" uma vez por turno."
    },
    "es": {
      "name": "Despertar Vaylantz - Activaci\u00f3n a Solas",
      "effect": "Pon 1 Monstruo de P\u00e9ndulo \"Vaylantz\" de tu Deck en tu Zona de P\u00e9ndulo. Si una carta est\u00e1 en una Zona del Campo: puedes desterrar esta carta en tu Cementerio, y despu\u00e9s selecciona 1 monstruo \"Vaylantz\" en tu Zona de Monstruos Principal; mueve ese monstruo que controlas a una Zona de Monstruos adyacente (horizontal). S\u00f3lo puedes usar cada efecto de \"Despertar Vaylantz - Activaci\u00f3n a Solas\" una vez por turno."
    },
    "ja": {
      "name": "\uff36\uff36\uff0d\u30bd\u30ed\u30a2\u30af\u30c6\u30a3\u30d9\u30fc\u30c8",
      "effect": "\u3053\u306e\u30ab\u30fc\u30c9\u540d\u306e\u2460\u2461\u306e\u52b9\u679c\u306f\u305d\u308c\u305e\u308c\uff11\u30bf\u30fc\u30f3\u306b\uff11\u5ea6\u3057\u304b\u4f7f\u7528\u3067\u304d\u306a\u3044\u3002\u2460\uff1a\u30c7\u30c3\u30ad\u304b\u3089\u300c\u30f4\u30a1\u30ea\u30a2\u30f3\u30c4\u300d\uff30\u30e2\u30f3\u30b9\u30bf\u30fc\uff11\u4f53\u3092\u9078\u3093\u3067\u81ea\u5206\u306e\uff30\u30be\u30fc\u30f3\u306b\u7f6e\u304f\u3002\u2461\uff1a\u30d5\u30a3\u30fc\u30eb\u30c9\u30be\u30fc\u30f3\u306b\u30ab\u30fc\u30c9\u304c\u5b58\u5728\u3059\u308b\u5834\u5408\u3001\u5893\u5730\u306e\u3053\u306e\u30ab\u30fc\u30c9\u3092\u9664\u5916\u3057\u3001\u81ea\u5206\u306e\u30e1\u30a4\u30f3\u30e2\u30f3\u30b9\u30bf\u30fc\u30be\u30fc\u30f3\u306e\u300c\u30f4\u30a1\u30ea\u30a2\u30f3\u30c4\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\uff11\u4f53\u3092\u5bfe\u8c61\u3068\u3057\u3066\u767a\u52d5\u3067\u304d\u308b\u3002\u305d\u306e\u81ea\u5206\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\u306e\u4f4d\u7f6e\u3092\u3001\u305d\u306e\u96a3\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\u30be\u30fc\u30f3\u306b\u79fb\u52d5\u3059\u308b\u3002"
    },
    "ko": {
      "name": "VV\uff0d\uc194\ub85c\uc561\ud2f0\ubca0\uc774\ud2b8",
      "effect": "\uc774 \uce74\ub4dc\uba85\uc758 \u2460\u2461\uc758 \ud6a8\uacfc\ub294 \uac01\uac01 1\ud134\uc5d0 1\ubc88\ubc16\uc5d0 \uc0ac\uc6a9\ud560 \uc218 \uc5c6\ub2e4. \u2460: \ub371\uc5d0\uc11c \"\ubc38\ub9ac\uc5b8\uce20\" \ud39c\ub4c8\ub7fc \ubaac\uc2a4\ud130 1\uc7a5\uc744 \uace0\ub974\uace0 \uc790\uc2e0\uc758 \ud39c\ub4c8\ub7fc \uc874\uc5d0 \ub193\ub294\ub2e4. \u2461: \ud544\ub4dc \uc874\uc5d0 \uce74\ub4dc\uac00 \uc874\uc7ac\ud560 \uacbd\uc6b0, \ubb18\uc9c0\uc758 \uc774 \uce74\ub4dc\ub97c \uc81c\uc678\ud558\uace0, \uc790\uc2e0 \uba54\uc778 \ubaac\uc2a4\ud130 \uc874\uc758 \"\ubc38\ub9ac\uc5b8\uce20\" \ubaac\uc2a4\ud130 1\uc7a5\uc744 \ub300\uc0c1\uc73c\ub85c \ud558\uc5ec \ubc1c\ub3d9\ud560 \uc218 \uc788\ub2e4. \uadf8 \uc790\uc2e0 \ubaac\uc2a4\ud130\uc758 \uc704\uce58\ub97c, \uadf8 \uc606\uc758 \ubaac\uc2a4\ud130 \uc874\uc73c\ub85c \uc774\ub3d9\ud55c\ub2e4."
    },
    "zh-CN": {
      "name": "\u5f08\u52c7\u89c9\u9192\uff0d\u5355\u4eba\u6fc0\u6d3b",
      "effect": "\u6b64\u5361\u540d\u7684\u2460\u2461\u6548\u679c\uff11\u56de\u5408\u4ec5\u53ef\u5404\u4f7f\u7528\uff11\u6b21\u3002\u2460\uff1a\u4ece\u724c\u7ec4\u6311\u9009\uff11\u53ea\u201c\u5f08\u52c7\u201d\u7075\u6446\u602a\u517d\u653e\u5728\u81ea\u5df1\u7684\u7075\u6446\u533a\u57df\u3002\u2461\uff1a\u573a\u5730\u533a\u57df\u6709\u5361\u5b58\u5728\u7684\u60c5\u51b5\u4e0b\uff0c\u5c06\u5893\u5730\u7684\u6b64\u5361\u9664\u5916\uff0c\u4ee5\u81ea\u5df1\u7684\u4e3b\u8981\u602a\u517d\u533a\u57df\u7684\uff11\u53ea\u201c\u5f08\u52c7\u201d\u602a\u517d\u4e3a\u5bf9\u8c61\u53ef\u4ee5\u53d1\u52a8\u3002\u5c06\u8be5\u81ea\u5df1\u7684\u602a\u517d\u7684\u4f4d\u7f6e\u79fb\u52a8\u81f3\u5176\u76f8\u90bb\u7684\u602a\u517d\u533a\u57df\u3002"
    }
  },
  "cardType": "spell",
  "subcategory": "normal",
  "passwords": [
    "60095092"
  ],
  "images": [
    {
      "id": "3f844b8d-ddb8-4e1f-b1d8-312644d65aff",
      "password": "60095092",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/60095092.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/60095092.jpg"
    }
  ],
  "sets": [
    "e7ef8e3a-7ae2-48b1-9b23-4d1a7729ee8e",
    "e7ef8e3a-7ae2-48b1-9b23-4d1a7729ee8e",
    "e7ef8e3a-7ae2-48b1-9b23-4d1a7729ee8e",
    "e7ef8e3a-7ae2-48b1-9b23-4d1a7729ee8e",
    "e7ef8e3a-7ae2-48b1-9b23-4d1a7729ee8e",
    "e7ef8e3a-7ae2-48b1-9b23-4d1a7729ee8e",
    "e7ef8e3a-7ae2-48b1-9b23-4d1a7729ee8e",
    "e7ef8e3a-7ae2-48b1-9b23-4d1a7729ee8e",
    "5499e80c-ce30-4c99-a080-f165a2a644ef",
    "6b51b0c5-edba-4322-8ede-176bc1efa365",
    "59b696ee-a190-4737-ae4a-d11a19c99d46",
    "6a8b667f-4688-46d0-a402-5743f2bacc09",
    "a89ad0db-a6bc-45a7-93ff-3f3c16d7024b"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited",
      "currentLegality": "unlimited"
    },
    "ocg": {
      "current": "unlimited",
      "currentLegality": "unlimited"
    },
    "genesys": {
      "current": "unlimited",
      "currentLegality": "unlimited",
      "currentPoints": 0
    }
  },
  "masterDuel": {
    "rarity": "sr",
    "craftable": true
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Vaylantz Wakening - Solo Activation",
        "id": 717368
      }
    ],
    "dbID": 17823,
    "ygoprodeck": {
      "id": 60095092,
      "name": "vaylantz-wakening-solo-activation-13399"
    },
    "yamlyugiID": 60095092
  },
  "series": [
    "b758e405-846d-4684-99e9-ad81a3aeb5f2"
  ]
}
